### ISSUE TITLE
Inconsistent hostname use in Crypto_PKI lab

### ISSUE THREAD

**Issue by jwalden** [seed-labs/seed-labs#10]
The Crypto_PKI Lab uses hostname SEEDPKILab2020.com but sometimes calls it SEEDPKILab2018.com. The lab should be modified to only refer to one of the two hostnames.

**Comment by kevin-w-du** [comment]
Thanks for raising this issue. I will fix it in the Ubuntu20.04 branch. I am trying to avoid making changes to the master branch, otherwise it will cause conflicts (the PKI lab las been revised quite significantly in the Ubuntu20.04 branch).

**Comment by kevin-w-du** [comment]
The problem is now fixed in Ubuntu 20.04.
