### ISSUE TITLE
CTF project link

### ISSUE THREAD

**Issue by cole-wustl** [seed-labs/seed-labs#108]
Here is some suggested language for the README file for including a link to the CTF project repo; feel free to use, modify, or not use at your discretion.  Here's a direct link the project in case it's helpful: https://github.com/cole-wustl/seed-labs-ctf 

Suggested language:

# Open-Source CTF Project

---

A set of Capture The Flag (CTF) challenges corresponding to individual
SEED Labs has been developed separately from the main SEED Labs project
and is maintained in the following GitHub repository:
[https://github.com/cole-wustl/seed-labs-ctf](https://github.com/cole-wustl/seed-labs-ctf).
Please visit the repository for details and instructions on how to
download/use the CTF platform.

**Comment by kevin-w-du** [comment]
Thanks. I have added it to the `category-ctf` folder.
