### ISSUE TITLE
openssl.cnf file not found

### ISSUE THREAD

**Issue by hooper625** [seed-labs/seed-labs#115]
Where can I fins the openssl.cnf file used in the lab? It is not on the VM, my computer, or zip folder.

**Comment by kevin-w-du** [comment]
Please describe the issue in more details. If you are reporting a problem in the SEED lab, this is the right place. If you are looking for the guidance on how to do the lab, this is not the place.

**Comment by hooper625** [comment]
I keep getting the error code [image: image.png] I do not know why. if I
put myCA in front of the opensl.cnf it's the same. I don't know if I am
using the right certificate or not because there are alot of sites with
this openssl information and I am lost. The directions are not clear. The
labs are not written in order and I become lost in translation. I spend
more time correcting errors than actually learning. Frustrating people who
are learning is the worst way to teach. I know I am a sped teacher.

Erika

**Comment by kevin-w-du** [comment]
Most people use this issue channel to provide suggestions that can help improve this open-source project. Your message does not really belong to that category. It seems that you are simply venting your frustration here. You described the problem you encountered while doing that lab, and blame the lab for that (without any specific evidence). Your message is rude and is not constructive, and we will not tolerate this kind of behavior. If you don't like our labs, you always have a choice not to use them. There is no need to send such a message using this channel. I am closing this issue right now.

**Comment by hooper625** [comment]
I was trying to figure out the problem that is why I needed to know where
to find the OpenSSL used in the lab. I have tried 3 different files and
have received three different error codes. The latest code is a version
update that has made a file directory not accessible.
