### ISSUE TITLE
Docker image issues on Mac M1.

### ISSUE THREAD

**Issue by rohanvp** [seed-labs/seed-labs#116]
Is the image "handsonsecurity/seed-ubuntu" used in certain labs working on Mac M1 laptops? I am having problems running a lab on Mac M1 and I think the image is not updated to support M1 architecture. If possible update all docker images to support multiple cpu architectures including Mac M1. Thanks.

**Comment by kevin-w-du** [comment]
For Mac M1/M2 laptops, before VirtualBox solves the problem, students are directed to use the cloud to do the SEED labs.  This has been done by students around the global for the last 3 years. Please read the instruction here for cloud setup: https://seedsecuritylabs.org/labsetup.html. This is not a problem that we can solve with our resources.
