### ISSUE TITLE
Inconsistency between the environment description for Crypto_PKI and Crypto_TLS

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#13]
Crypto PKI is a prerequisite of Crypto TLS. 
However, the Crypto TLS lab has been tested on 20.04 VM, while the Crypto PKI has only 16.04 VM.

**Comment by kevin-w-du** [comment]
I was planning to release the Ubuntu 20.04 version of all the SEED labs tomorrow. I will merge the ubuntu20.04 branch into the master branch (about 340 commits will be merged into master). You may have to revise the translation based on the new version. I have been working on this for the last 6 months.

**Comment by LuminousXLB** [comment]
Okay, I'll do that for the labs that I've translated.
