### ISSUE TITLE
Problem Docker compose

### ISSUE THREAD

**Issue by joelalves** [seed-labs/seed-labs#135]
Problem with docker compose up
Apple M2 Pro
MacOs 14.2.1
seed_postgres  | 2024-01-11 20:45:00.168 UTC [1] LOG:  listening on IPv6 address "::", port 5432
seed_postgres  | 2024-01-11 20:45:00.170 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/seed/docker/start_celery_docker.sh": stat /seed/docker/start_celery_docker.sh: no such file or directory: unknown

**Comment by kevin-w-du** [comment]
We are not ready to support Apple M1/M2 platform. We are working on that. Let me know which lab you are working on. Chances are that with a minor change, you can make it work.

**Comment by joelalves** [comment]
Thanks. For make my student work i used other mac with intel processor.
