### ISSUE TITLE
Android Labs are not Supported on ARM 

### ISSUE THREAD

**Issue by cfossace** [seed-labs/seed-labs#139]
The Android lab provides an x86 VM, which can't run on ARM. I noticed this wasn't being tracked in the ARM updates -- is an ARM version of the custom VM going to be released, or an Android ARM alternative pointed to for the ARM labs?

**Comment by kevin-w-du** [comment]
Due to the lack of man power and the difficulties of maintaining the Android labs, we no longer support them. That is why the labs and the platform have not been updated for many years.

**Comment by vnijat93** [comment]
not something you wanna see when your grades depend on this

**Comment by kevin-w-du** [comment]
Your instructor should have known this before assigning the lab to you.

**Comment by cfossace** [comment]
Thanks for the reply back. I think maybe it should be listed somewhere that these labs are no longer supported? Since many professors seem to be using them.

**Comment by kevin-w-du** [comment]
Thanks for the suggestion. I have added a note to the mobile security lab's web page.
