### ISSUE TITLE
Customized alias set in the .bashrc

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#14]
It seems that writing the aliases in a separate file like `~/.bash_aliases` could be better than directly adding them to `.bashrc`.
Because it's easier for the users to turn to zsh or other shells and import to the file directly.

**Comment by kevin-w-du** [comment]
That's a good idea. I never used `.bash_aliases` before, but it is definitely a better way to add aliases. I will do that when I update the VM. Thanks for the suggestion.

**Comment by kevin-w-du** [comment]
I have added a note to the `lab-setup/ubuntu20.04-vm/TODO.md` file regarding this suggestion. Although the issue won't be resolved until the next VM release, we can consider this issue closed. Therefore, I am closing the issue.
