### ISSUE TITLE
VM Issue

### ISSUE THREAD

**Issue by MakenaEurydice** [seed-labs/seed-labs#158]
My VM suddenly stopped working with the error below. I have uninstalled and reinstalled it several times with the same error. I have also tried it on two other computers but I receive the same error immediately after logging in.

![image](https://github.com/user-attachments/assets/669c3faf-d14f-4f39-8d84-c632ed2d2983)

**Comment by dstkibrom** [comment]
Hello I have had the same issue but mine got resolved when i uncheked the Extended Features: Enable 3D Acceleration. 
you might as well try that one and see if it works for you. 
![Screenshot from 2024-12-27 10-15-51](https://github.com/user-attachments/assets/51b97682-57e8-4456-9dd4-85c5c89d9e85)

**Comment by kevin-w-du** [comment]
Thanks for making the suggestion.

**Comment by MakenaEurydice** [comment]
I was able to resolve it a while and forgot to update the ticket, my apologies. I tried to reinstall the VM like I would a normal one without following the guide and that worked. I just checked and turns out I didn't check the Extended features box, so that might be what was causing it. Thank you @dstkibrom
