### ISSUE TITLE
Crypto_PKI: Potential typos

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#16]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_PKI/Crypto_PKI.tex#L378

I think it's the generated certificate, instead of the key, which should be printed

**Comment by LuminousXLB** [comment]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_PKI/Crypto_PKI.tex#L546

The `ServerName` seems to be `www.example.com` instead of `example.com`

**Comment by kevin-w-du** [comment]
I fixed both typos and have committed it to the master branch. Thanks.
