### ISSUE TITLE
Crypto_TLS: Potential Typos

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#20]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_TLS/Crypto_TLS.tex#L219-L244

The directory for our own certificate store has inconsistent names.

**Comment by kevin-w-du** [comment]
Fixed. Thanks.

**Comment by LuminousXLB** [comment]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_TLS/Crypto_TLS.tex#L694

I think it should be the attacker container?

**Comment by kevin-w-du** [comment]
Yes, that's a typo. I changed it to "attacker's machine", which covers both container and VM cases (just in case some students use VMs instead of containers to do this lab). Thanks.
