### ISSUE TITLE
Crypto_TLS: dig command not found in medium image

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#21]
The lab used [handsonsecurity/seed-ubuntu:medium](https://github.com/seed-labs/seed-labs/blob/master/lab-setup/docker-images/seed-ubuntu/medium/Dockerfile) to be the client machine and requires to run `dig` command in Task 1.c.
However, `dnsutils` is not installed in this docker image.

**Comment by kevin-w-du** [comment]
I added a note to the lab description regarding the dig command, which should be executed on the VM, not the container. I am trying to minimize the size of the container image by not installing unnecessary software. That is the reason I have `small`, `medium`, and `large` images for `seed-ubuntu`. The `large` image contains the `dig` tool.
