### ISSUE TITLE
Crypto_MD5_Collision: Potential Typos

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#22]
According to [md5_firsttime.sh](https://github.com/seed-labs/seed-labs/blob/master/lab-setup/ubuntu20.04-vm/src/md5_firsttime.sh#L24), you've installed `md5collgen` into /usr/bin instead of [`/home/seed/bin`](https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_MD5_Collision/Crypto_MD5_Collision.tex#L93)

**Comment by LuminousXLB** [comment]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_MD5_Collision/Crypto_MD5_Collision.tex#L284

Since it's a cryptographic lab, I think *arbitrary value* can be a better statement than *random value*

**Comment by kevin-w-du** [comment]
I fixed both typos in the lab description. Thanks.
