### ISSUE TITLE
Crypto_Hash_Length_Ext: why is there a duplicate copy of code

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#23]
https://github.com/seed-labs/seed-labs/tree/master/category-crypto/Crypto_Hash_Length_Ext

I find that there's a copy in `Code` directory, and another copy in `Labsetup/image_flask`. 
Why are there two copies?

**Comment by kevin-w-du** [comment]
This copy will not be used. I have added a README file in this folder. Eventually, I will remove it, but not for now.
