### ISSUE TITLE
Crypto_Encryption: Potential Typos

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#26]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_Encryption/Crypto_Encryption.tex#L163

`fro` seems to be `from`

**Comment by LuminousXLB** [comment]
https://github.com/seed-labs/seed-labs/blob/master/category-crypto/Crypto_Encryption/Crypto_Encryption.tex#L271

Why do we say PKCS#5 is the _standard block padding_? I searched the web but find little about the term _standard block padding_.

**Comment by kevin-w-du** [comment]
You are right, I have rephrased that sentence.
