### ISSUE TITLE
Crypto_Encryption: Encryption Oracle for Task 6.3

### ISSUE THREAD

**Issue by LuminousXLB** [seed-labs/seed-labs#33]
Task 6.3. Common Mistake: Use a Predictable IV

I'm thinking about adding a docker container which does the encryption with given IV and key.
The daemon can be written in C++ with Openssl and distributed to students in binary format.
Students may interact with the container by command line or socket.
This may help to protect the IV and key from being known by students.

Based on this, it's also possible to develop a padding oracle attack lab against CBC mode.

**Comment by kevin-w-du** [comment]
This is a very good idea. That will make the lab more interesting. Please go ahead.

**Comment by kevin-w-du** [comment]
I like the design that you provide. I have a few suggestions. Let's move this discussion to `Discussions`, instead of in `Issues`.
