### ISSUE TITLE
Containerizing SEED Labs

### ISSUE THREAD

**Issue by kevin-w-du** [seed-labs/seed-labs#4]
Most of the SEED labs in the network security category requires multiple VMs, some, such as VPN, requires 3 to 4 VMs. While this is doable for most of the computers, it does put stress on many computers, especially those with limited amount of RAM and cores. Containers can be used to solve this problem.

For these labs, I would like to create a container version (we will keep the VM version). This will only affect the lab environment setup usually put at the beginning of each lab. The task is to add instructions to the lab description to help students easily setup the environment. We will use docker. 

I have created a few new labs based on containers. These labs do not work for the VM, because they need 6 to 10 machines, some may need up to 20. Container is good for them (we just need one VM). These labs serve as an example of how the container technology is used in the SEED labs. These two labs are "_DNS in a Box_" and "_DNSSEC_" (in the network category). They are both working in progress, and have not been officially released.

**Comment by kevin-w-du** [comment]
This work is done.

**Comment by Clifnich** [comment]
AWS also provides [container services](https://aws.amazon.com/ecs/) using which you can bring up several instances within a VPC and do labs on it. If people have trouble installing and configuring Docker on their computers, using the cloud can be a fallback option.

**Comment by Tweeks-va** [comment]
Hey guys.. At the Cyber Range, we've stayed away from marrying ourselves to AWS' container service for student facing containers.. Instead.. we create a second "container VM" and roll out customer containers on that VM.. and expose new container VM IPs and DNS mapping..  Want to discuss?

**Comment by kevin-w-du** [comment]
I am using the same approach as Tweeks. Students do need to have a VM, and then run containers inside the VM to do the lab. The VM is an essential piece of the lab, and it is not just for hosting containers. Without the VM, many labs won't work (some labs can be done). Another important reason is that I don't want students to install unnecessary software on their computers, because that will become instructor's nightmare.

**Comment by Tweeks-va** [comment]
Kevin.. do you prefer to have containers on the same VM as the desktop/client (for DNS)... or a separate, dedicated container VM?

**Comment by kevin-w-du** [comment]
I prefer to have containers on the same VM. This way, students only need one VM.
