### ISSUE TITLE
Need to update link or target website for setup instructions. 

### ISSUE THREAD

**Issue by traviswpeters** [seed-labs/seed-labs#46]
The "SEED Website" link on this page (https://github.com/seed-labs/seed-labs/blob/master/manuals/vm/seedvm-manual.md#preparation) does not appear to have the SEED-Ubuntu20.04.zip file, but the instructions suggest otherwise.

**Comment by kevin-w-du** [comment]
Thanks. The URL has changed, but I forgot to change the URL in this manual. It is fixed now.
