### ISSUE TITLE
Cross-site Scripting Attack (Elgg) doesn't have the correct lab setup archive

### ISSUE THREAD

**Issue by vini-fda** [seed-labs/seed-labs#74]
The linked file [on the XSS page on seed-labs](https://seedsecuritylabs.org/Labs_20.04/Files/Web_XSS_Elgg/Labsetup.zip) seems to be incomplete/wrong. SHA256SUM: 085e023d87371d0131364d9d36c8186adba6c668491f5d87af82380d58ec07e7.

As I tried using it(on the Ubuntu 20.04 seed VM), the website was incorrectly built, and all HTTP requests made to it were taking too long to process, even though the containers were correctly built.

One of the problems in that setup folder seems to be the fact that it pulls from `handsonsecurity/seed-elgg:original` instead of `handsonsecurity/seed-elgg:xss`(in the `image_www/Dockerfile` file), so it may leave incomplete configurations for the 20.04 version of the lab.

**Comment by vini-fda** [comment]
Using this setup file seems to fix all the issues: https://ufile.io/oh0tbkq8.

SHA256SUM: f6675d1aaf3cb3ad0bdf38be9465e044ff758d98ed2f9e8dfcf55e05c606f0d7

**Comment by kevin-w-du** [comment]
I could not recreate the errors reported by you. None of us in the workshops (2 weeks ago) had encountered this problem. Therefore, I believe this may be an issue on your side.

**Comment by kevin-w-du** [comment]
The docker image is supposed to pull from handsonsecurity/seed-elgg:original, instead of from seed-elgg:xss. We don't even have the seed-elgg:xss image any more (it was used in the past, but not now).
