### ISSUE TITLE
Dead link returns 404

### ISSUE THREAD

**Issue by TychoTheTaco** [seed-labs/seed-labs#81]
The following link returns a 404. Maybe it should be removed/replaced?
https://github.com/seed-labs/seed-labs/blob/603917bcfaaac832f9fd8e5ad946d61d59e6eec2/category-crypto/Crypto_Encryption/Crypto_Encryption.tex#L177

**Comment by kevin-w-du** [comment]
Thanks for reporting the broken link. I have removed the link. Since this website is essential for the lab task, after removing this link, I wrote a Python program to calculate the n-gram statistics, so we no longer need this website. The Python program is included in the `Labsetup/Files` folder.
