### ISSUE TITLE
Bug: missing a terminator in ($DNS_Reomte)/attack.c

### ISSUE THREAD

**Issue by Jacob953** [seed-labs/seed-labs#91]
Follow: #83 
**Bug description**
It would be unsafe with the index out of range [5] with length 5.

**Reproduce**
Just print the random name which attack.c generated.

**Additional text**
- I'm sorry for my irresponsible operations since it was when I began to take a part in open-source.
- And It's my bad for forgetting to maintain #83 when other important things came.

I'll reopen another PR to fix this. ;)

**Comment by kevin-w-du** [comment]
I have merged your fix. Really appreciate your help.
